src/arden.scc
src/arden/compiler/Compiler.java
src/arden/compiler/MetadataCompiler.java

An error is now shown when invalid values (not in range 1..99) are given for urgency and priority.
Invalid length (>80 characters) for mlmname, institution and version slot now lead to and error.
The title and version slot can now be empty. This was mentioned in the paper as an error because it happened for one of the tested mlms, but is actually required as per the specification:
> "For required textual slots, the text may be empty."

Fix bugs in textual slots

---

README.md
src/arden/compiler/ParseHelpers.java
src/arden/compiler/UnaryOperatorCompiler.java
src/arden/runtime/ArdenTime.java
src/arden/runtime/ExpressionHelpers.java
src/arden/runtime/UnaryOperator.java

This fixes primary time bugs for these operators:
- `INTERVAL`
- `MAX`, `MIN`, `INDEX MAX`, `MIN ... FROM`, etc.
- `MEDIAN`
- objects
Datetime constants should now be correctly interpreted:
- lowercase 't' and 'z' are now allowed
- the ISO 8601 timezone extensions ('Z', '+01:00', '-01:00') are now supported
This also fixes `LATEST ... FROM` returning the same as `EARLIEST ... FROM`.

Fix bugs related to primary time

---

test/arden/tests/specification/Operators/NumericFunctionOperatorsTest.java
test/arden/tests/specification/StructureSlots/ActionSlotTest.java
test/arden/tests/specification/StructureSlots/DataSlotTest.java
test/arden/tests/specification/StructureSlots/TokensTest.java
test/arden/tests/specification/testcompiler/SpecificationTest.java

This fixes `testIncludeStatment()` so it checks  whether Object Declarations are overwritten after an `INCLUDE`.
Also fixes a possible precedence bug in `testAsNumber()`, adds a whitespace test to `testComments()` and adds better assert messages.

Test fixes and improvements

---

test/arden/tests/specification/README.md
test/arden/tests/specification/operators/StringOperatorsTest.java
test/arden/tests/specification/structureslots/ActionSlotTest.java
test/arden/tests/specification/structureslots/TokensTest.java
test/arden/tests/specification/testcompiler/SpecificationTest.java
test/arden/tests/specification/testcompiler/TestCompiler.java

This allows parsers (e.g. IDEs like [Arden4Eclipse] (https://github.com/PLRI/ardensyntax-eclipse-plugin)) or compilers without runtime support to run all tests.
Tests which require runtime support then just check whether the code is correctly parsed (or an expected compiletime error is returned) and expected return values are ignored.
Also fixes two minor test bugs.

Tests update

---

LICENSE.md

The JewelCli library is not contained in the source code since dependency management was added (#19). It is however contained in the releases, so the license should be added again.

Add JewelCli license

---

build.xml

When building the distributables, the .java files are contained in the jar-file by default. This allows easy source lookup, for example when adding Arden2ByteCode as a library to a an Eclipse project. 
It can be disable via the `dist.source` property.

Attach source

---

build.xml
run.sh
src/arden/CommandLineOptions.java
src/arden/MainClass.java
test/arden/tests/implementation/CliTest.java

This adds automatic wrapping and indentation for the command line `--help` message, so this has not to be done by hand every time a description is updated or a new parameter is added. 
Wrapping is currently set to 80 characters, as 80*24 seem to be the usual terminal dimensions.
I also added a bash run script for visual inspection in a terminal, instead of the eclipse console or creating a jar every time.

Help message wrapping

---

src/arden/CommandLineOptions.java
src/arden/MainClass.java

This	 replaces the outfile **-o** option with an outdir **-d** option, similar to javac.
Choosing an output directory for compiled MLMs will likely happen more often, than naming a single output file. 
The shorter database driver option is now **--db**.
I also shortened the help message a bit, as the examples would not be helpful without looking at the command line reference page on the homepage/wiki.
The --help option should output brief documentation for how to invoke the program. Specifics should be in the documentation (e.g. the "Arguments" or "Using databases" wiki page).

Command line changes

---

src/arden/runtime/ExpressionHelpers.java
src/arden/runtime/evoke/CyclicTrigger.java

It was only possible to use triggers like this:
- `EVERY 1 SECONDS FOR 2 WEEKS STARTING 2016-07-16T16:21:00`
Now the following is possible:
- `EVERY 5 SECONDS FOR 1 MINUTE STARTING TIME OF an_event`
- `EVERY 5 SECONDS FOR 1 MINUTE STARTING 10 SECONDS AFTER THE TIME OF an_event`

Fix CyclicTrigger only supporting fixed time triggers

---

src/arden.scc
src/arden/compiler/Compiler.java
src/arden/compiler/EvokeCompiler.java

This add some reserved words as terminals, thereby preventing them from being used as identifiers.

Fix some reserved words being usable as identifiers

---

src/arden/compiler/InMemoryClassLoader.java

This fixes a rare bug, that happens when the MedicalLogicModuleImplementation class was not loaded yet, when an MLM's bytecode is loaded.
This bug only seems to happen with the Eclipse Java compiler.

Fix NoClassDefFoundError

---

src/arden.scc
src/arden/compiler/Compiler.java
src/arden/compiler/MetadataCompiler.java
src/arden/runtime/MaintenanceMetadata.java
test/arden/tests/implementation/LoadMlmFromBytecodeTest.java
test/arden/tests/implementation/MetadataTest.java
test/arden/tests/specification/testcompiler/impl/TestContext.java

This adds the possible values for the `validation:`  and `arden:` slot as enums, for easier comparison.

Metadata enums

---

src/arden/compiler/Compiler.java
src/arden/compiler/DataCompiler.java
src/arden/runtime/BaseExecutionContext.java
src/arden/runtime/ExecutionContextHelpers.java
test/arden/tests/specification/testcompiler/impl/TestCompilerImpl.java
test/arden/tests/specification/testcompiler/impl/TestContext.java
test/arden/tests/specification/testcompiler/impl/TestEngine.java

This adds the MLM search algorithm as a static method in a execution context helper class. Also the institution given to the context's `findModule()` method is now never `null` as it is the calling MLM's institution if not specified.
The BaseExecution context now searches for all MLMs with a matching filename, initializes them and then uses the algorithm, which also looks at the institution, version, etc. Previously only the filename was used to find MLMs. This answers my question (#39) about not initializing every MLM on the classpath and still finding the correct one.

Implement MLM search algorithm

---

README.md
src/arden/compiler/DataCompiler.java
src/arden/compiler/ExecutionContextMethods.java
src/arden/compiler/MessageVariable.java
src/arden/runtime/ExecutionContext.java
src/arden/runtime/StdIOExecutionContext.java
src/arden/runtime/jdbc/JDBCExecutionContext.java
test/arden/tests/implementation/TestContext.java
test/arden/tests/specification/testcompiler/impl/TestContext.java
test/arden/tests/specification/testcompiler/impl/TestEngine.java

This adds support for the `MESSAGE AS object_type {mapping}` and `DESTINATION AS object_type {mapping}` statements.
Execution contexts simply need to implement the
```java
public ArdenObject getDestinationAs(String mapping, ObjectType type)
```
and 
```java
public ArdenObject getMessageAs(String mapping, ObjectType type)
```
methods.

Support MESSAGE/DESTINATION AS

---

src/arden/compiler/DataCompiler.java

When an MLM does not use the `RETURN` statement, `null` (java) is returned, instead of an array of ArdenValues.
A calling MLM that tries to use the return values, would check the array length of this `null` array, which leads to a Nullpointer Exception.

Fix NullpointerException for no return values

---

src/arden/compiler/Compiler.java
src/arden/compiler/ErrorAnalysis.java

SableCC doesn't support variable length tokens, so the length is checked in java, after the tokens have been generated.

Fix identifiers with length > 80 being supported

---

src/arden/EventServer.java
src/arden/compiler/ActionCompiler.java
src/arden/compiler/CallableVariable.java
src/arden/compiler/DataCompiler.java
src/arden/compiler/EventVariable.java
src/arden/compiler/ExecutionContextMethods.java
src/arden/compiler/InterfaceVariable.java
src/arden/compiler/MedicalLogicModuleVariable.java
src/arden/compiler/MessageVariable.java
src/arden/runtime/BaseExecutionContext.java
src/arden/runtime/ExecutionContext.java
src/arden/runtime/ExecutionContextHelpers.java
src/arden/runtime/RuntimeHelpers.java
src/arden/runtime/StdIOExecutionContext.java
src/arden/runtime/jdbc/JDBCExecutionContext.java
test/arden/tests/implementation/TestContext.java
test/arden/tests/specification/testcompiler/impl/TestContext.java
test/arden/tests/specification/testcompiler/impl/TestEngine.java

When an MLM or event is called, or when a message is written, the `urgency` slots value is now available to the `ExecutionContext`.
This slot may contain a constant number (between 1 and 99) or may reference a variable. If a variable is used, its value at the time the `WRITE` or `CALL` statement is made is used. This allows changing the urgency for every action separately.

Use urgency for actions

---

src/arden/MainClass.java
src/arden/engine/Call.java
src/arden/engine/EventCall.java
src/arden/engine/EvokeEngine.java
src/arden/engine/MlmCall.java
src/arden/engine/Schedule.java
src/arden/runtime/BaseExecutionContext.java
test/arden/tests/specification/testcompiler/impl/TestEngine.java

This splits the evoke engine into multiple classes, which now reside in the `arden.engine` package.
`MlmCall`, `EventCall` and `Schedule` are now separate from the engine and can be reused in other engines.
The core mechanism of the engine can now easily be changed (e.g. cron jobs, instead of `ScheduledExecutorService`), without needing to rewrite the scheduling logic.

Make evoke engine reusable

---

src/arden/runtime/jdbc/JDBCQuery.java

Supported types:
- null (previously produced an error)
- boolean
- string
- number (int, float, short, ...)
- date (timestamp, datetime, etc.)
Other database-specific types are returned as strings.

Update JDBCQuery to support more datatypes

---

src/arden/compiler/DataCompiler.java
src/arden/compiler/ExecutionContextMethods.java
src/arden/compiler/ReadPhraseCompiler.java
src/arden/runtime/ExecutionContext.java
src/arden/runtime/StdIOExecutionContext.java
src/arden/runtime/jdbc/JDBCExecutionContext.java
test/arden/tests/implementation/ExampleEvokeTest.java
test/arden/tests/implementation/ExampleTest.java
test/arden/tests/implementation/LoadMlmFromBytecodeTest.java
test/arden/tests/implementation/TestContext.java
test/arden/tests/specification/testcompiler/impl/TestContext.java
test/arden/tests/specification/testcompiler/impl/TestEngine.java

This allows reading the MLMs variables in mappings, as mentioned in the specification.
Also allows access to the evoking event, e.g. to return data associated with that event.

Add calling MLM as parameter to all mapping methods

---

.travis.yml
src/arden/compiler/FormattingCompiler.java
src/arden/compiler/HexadecimalFormat.java
src/arden/compiler/OctalFormat.java
test/arden/tests/specification/operators/StringOperatorsTest.java

- Now supports all specified format specifiers
- Allows the use of lower and upper case specifiers
- Adds support for hexadecimal
(%x: lowercase [a-f], %X: uppercase [A-F])
- Adds support for octal (%o, %O)
- Adds support for scientific representation
(%e: lowercase e-exponent, %E: uppercase E-exponent)
- Adds basic support for (%g and %G), though only as alias to %f resp %F

Improves handling of 'formatted with'
